

FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11

# Set working directory
WORKDIR /app

COPY ./scoring /app

# Install dependencies
COPY requirements-fastapi.txt .
RUN pip install --no-cache-dir -r requirements-fastapi.txt

# Expose FastAPI default port
EXPOSE 8000

CMD ["uvicorn", "scoring.app.main:app", "--host", "0.0.0.0", "--port", "8000"]