version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: marketing_mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: marketing_db
      MYSQL_USER: marketing_user
      MYSQL_PASSWORD: marketing_pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
