

apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: marketing-analytics-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          # volumeMounts removed
      # volumes removed